name: Test
on:
  workflow_dispatch:
    inputs:
      url: 
        description: url to GET tarball patch from
        type: string
    



jobs:
  edit-article:
    runs-on: ubuntu-latest
    steps:
      - name: Unpack Changes
        run: |
          curl -o PATCH.tar.gz "${{inputs.url}}"
          tar -xzf PATCH.tar.gz
          rm PATCH.tar.gz
          file .