name: Test
on:
  workflow_dispatch:
    inputs:
      data: 
        description: base64 tarball of changed files
        type: string



jobs:
  edit-article:
    runs-on: ubuntu-latest
    steps:
      - name: Unpack Changes
        run: |
          touch PATCH.tar.gz
          echo "${{ inputs.data }}" | base64 --decode > PATCH.tar.gz
          tar -xzf PATCH.tar.gz
          rm PATCH.tar.gz
          file .